baseURL = "https://tililablog.netlify.app/"
disqusShortname = ""
googleAnalytics = ""
paginate = "5"
summaryLength = "20"
theme = "apollo"
title = "Izza Tilila"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "About"
url = "about/"
weight = 1
[[menu.main]]
name = "Elemetns"
url = "elements/"
weight = 2
[[menu.main]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 3
[[menu.main]]
name = "Contact"
url = "contact/"
weight = 4
[outputs]
home = ["HTML", "RSS"]
[params]
author = "https://fontmeme.com/permalink/220726/087d5205b8311da65f58e30d93c7dd91.png"
banner_content = "كاتبة وصانعة محتوى و شخصية عامة. يمكنني إلقاء نظرة على حياتي والحصول على قصة جيدة للخروج منها. إنها صورة شخص يحاول معرفة الأشياء."
copyright = "        Izzatilila.com © 2022 | Designed & Developed By [Akselinc](https://akselinc.com/)"
custom_script = ""
description = "This is meta description"
favicon = "images/favicon.png"
logo = "images/logo.png"
logo_width = "100px"
main_section = "post"
[params.cookies]
enable = false
expire_days = 2
[[params.plugins.js]]
link = "https://unpkg.com/eslint-plugin-rtl@0.1.1/lib/index.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
[params.variables]
black = "#000"
body_color = "#fff"
border_color = "#e2e2e2"
icon_font = "Fontawesome 5 Free"
light = "#f1f1f1"
primary_color = "#33186D"
primary_font = "DM Sans:400,500,700"
text_color = "#333"
text_color_dark = "#000"
text_color_light = "#999"
white = "#fff"
[[params.social]]
icon = "fab fa-youtube"
link = "https://www.youtube.com/channel/UCz-lgnYzmetoHgV8FrcSScQ"
title = "youtube"
[[params.social]]
icon = "fab fa-tiktok"
link = "https://tiktok.com/izzatilila"
title = "tiktok"
[[params.social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/izzatilila"
title = "facebook"
[[params.social]]
icon = "fab fa-twitter"
link = "https://twitter.com/izzatilila"
title = "twitter"
[[params.social]]
icon = "fab fa-instagram"
link = "https://instagram/izzatilila"
title = "instagram"
[[params.social]]
icon = "fab fa-pinterest"
link = "https://pinterest.com/izzatilila"
title = "pinterest"
[[params.social]]
icon = "fab fa-linkedin"
link = "https://linkedin.com/izzatilila"
title = "linkedin"
